title: Home

resources:
  - url: /customcards/github/maykar/compact-custom-header.js?track=true
    type: module
  - url: /customcards/github/custom-cards/tracker-card.js?track=true
    type: module

# Compact Custom Header
cch:
  options: show

# background: center / cover no-repeat url("/local/background2.jpeg") fixed
views:
  - !include lovelace/home.yaml
  - !include lovelace/weather.yaml
  - !include lovelace/discover.yaml
